[marketplaces.mindthus-roi-r1]
last_updated = "2026-07-19T06:22:56Z"
source_type = "local"
source = "/private/var/folders/kf/bs17ldg51nbd7hjg2685pps40000gn/T/mindthus-roi-convergence-live-glbh6nib/r1-pack"

[plugins."mindthus@mindthus-roi-r1"]
enabled = true
