[marketplaces.mindthus-roi]
last_updated = "2026-07-19T05:10:05Z"
source_type = "local"
source = "/private/var/folders/kf/bs17ldg51nbd7hjg2685pps40000gn/T/mindthus-roi-live-jeum774b/candidate-pack"

[plugins."mindthus@mindthus-roi"]
enabled = true
