[marketplaces.mindthus-roi-r2]
last_updated = "2026-07-19T07:02:24Z"
source_type = "local"
source = "/private/var/folders/kf/bs17ldg51nbd7hjg2685pps40000gn/T/mindthus-roi-convergence-live-v5xp2t6g/r2-pack"

[plugins."mindthus@mindthus-roi-r2"]
enabled = true
